src/app/styles/app.css, src/autodetect/index.js, src/compiler/compiler.js, src/index.html, src/renderer.js, src/session/feed.js, src/session/session.js, src/session/streams.js, src/storage/custom-css.js, src/vimish/index.js
adds some initial legwork around the `:stream` command
`:stream <name> <state>`
examples:
```
:stream thoughts on
:stream speech off
:stream logon 1
:stream logoff 0
```
=> feat: split streams

src/app/styles/app.css, src/app/ui/cli.js, src/compiler/compiler.js, src/renderer.js, src/session/feed.js, src/session/session.js, src/session/state.js
also went ahead and added `roomName` (colloquially known as room title) to the `state` object
=> feat: roundtime trackers

README.md, src/app/styles/app.css, src/app/ui/index.js, src/app/ui/layout.js, src/index.html, src/session/streams.js
My thinking here is that there is _lots_ of opportunity and potential with the Panels system. Main feed in the middle, surrounded by left and right sidebars full of panels (ultimately, rearrangeable, resizeable, and reorderable). People can really customize the UI to what is important to them with Panels. 
ESP is a great candidate for a Panel, so this PR puts it over in the (new) right-side Panel area. 
Although if that's the case, it should probably use the standard Panel system that is already in place.
=> (Optional, As-Yet-Unused) Right-Side Panels

README.md, src/app/styles/app.css, src/app/ui/sessions.js
=> Sessions UI

src/app/styles/app.css, src/app/ui/flash-message.js, src/app/ui/index.js, src/index.html, src/renderer.js, src/session/session.js
adds a global flash message system on `window.messages`
=> feat: add flash message system

src/app/styles/app.css, src/app/ui/flash-message.js, src/bus/index.js, src/renderer.js, src/storage/custom-css.js, src/vimish/index.js
also adds support for `.info` `.error` and `.ok` flash messages
=> feat: add :reload-skin command

src/app/ui/hud/stance.js
Adds an ID to the stance bar (for hanging styles off) in the vitals HUD.
=> adds id to the stance bar in vitals HUD

package.json, src/main.js, yarn.lock
#58 
Defines a defaults, saves the users arrangement on close, loads saved state on launch.
=> save and set window state

src/app/styles/themes/icemule.scss
=> Updates Icemule theme

src/app/ui/hud/active-spells.js, src/constants/spells/index.js
This is all Bryan's work, I just ported it to the architectural structure that was discussed.
=> Add spell details as data attributes

README.md, src/app/styles/_feed.scss, src/app/styles/_layout.scss, src/app/styles/_sessions.scss, src/app/styles/_streams.scss, src/app/styles/_util.scss, src/app/styles/themes/dark-king.scss, src/app/styles/themes/kobold.scss, src/app/styles/themes/original.scss, src/app/styles/themes/raging-thrak.scss, src/app/styles/themes/rogue.scss, src/app/ui/cli.js
Nothing incredibly significant. More variablization and fallbacks. The `translate` on the feed makes it render better for me. README updates.
=> Theme Updates

src/app/styles/_feed.scss, src/app/styles/_streams.scss, src/app/ui/flash-message.js, src/renderer.js, src/session/session.js, src/session/streams.js, src/storage/schema.js, src/vimish/commands/connect.js
This seems pretty straightforward, assuming `Storage` is the right place for this?
If so, I just need to make sure to trim the storage to a reasonable level and then deal with storage on a per-account basis.
=> Storage of Streams

src/session/state.js
followup fix for id-based key values
=> fix: use calculated id for state keys;

src/app/ui/cli.js, src/session/feed.js, src/session/session.js
=> feat: fixup prompts to redraw more;

src/parser/index.js, src/session/session.js
=> fix: better handle leading and trailing linebreaks; 

.eslintrc.yml, package.json, yarn.lock
This adds ESLint for code linting, and integrates it with prettier so the two will not conflict.
=> Add ESlint for code linting

src/session/session.js
If localhost doesn't exist in the DNS, fallback to 127.0.0.1. This resolves an issue for macOS where it isn't defined by default, but if someone were to delete the hosts entry, this would still safely fallback.
=> Add fallback logic if localhost doesn't exist.

.eslintignore, .eslintrc.yml, package.json, src/app/ui/cli.js, src/app/ui/hud/vitals.js, src/app/ui/progress.js, src/autocomplete/autocomplete.js, src/autocomplete/qwerty.js, src/macros/macros.js, src/main.js, src/session/feed.js, src/session/session.js, src/storage/index.js, src/storage/schema.js, src/util/list.js, src/util/redraw.js, src/vimish/commands/compiler.js, src/vimish/commands/connect.js, src/vimish/commands/explain.js, src/vimish/commands/focus.js, yarn.lock
This PR more extensively configures ESLint, including pointing it at the files in `src`, causing it to identify a number of issues. This PR also starts trying to clean those up, though is still a work in progress.
=> Improve ESLint configuration, and fix violations.

.travis.yml, package.json, src/session/command-history.js, src/util/time.js, test/command-history.test.js, test/time.test.js, yarn.lock
This adds jest as a testing framework, and adds a unit test for `src/util/time.js`. This also fixes the formatting of negative time durations in that file.
=> Unit test time.js using jest.

README.md
This PR attempts to document the `hilite` and `config` commands.
=> Document hilite and config commands

README.md, src/app/styles/_hilite.scss, src/hilites/index.js, src/vimish/commands/compiler.js, src/vimish/commands/hilite.js, src/vimish/commands/sudo.js
This implements the very basic functionality for removing highlights and groups.
=> Support removing patterns and groups

src/app/styles/themes/icemule.scss, src/constants/spells/spells.json
Style updates for Icemule theme.
=> style(theme): icemule updates

package.json, src/session/feed.js, yarn.lock
=> Fix hidpi scrolling
